server:
  port: 8092

spring:
  main:
    web-application-type: reactive
  application:
    name: ApiGatewayApplication
  cloud:
    gateway:
      routes:
        - id: UserApplication
          uri: lb://UserApplication
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: CartApplication
          uri: lb://CartApplication
          predicates:
            - Path=/carts/**
        - id: RestaurantApplication
          uri: lb://RestaurantApplication
          predicates:
            - Path=/restaurants/**
          filters:
            - AuthenticationFilter
        - id: Service-Discovery
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: Service-Discovery-Static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
#          filters:
#            - RewritePath=/example1/(?<segment>.*), /$\{segment}




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO