server:
  port: 8088

spring:
  application:
    name: PaymentApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/es_payment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka